### PR TITLE
add harvest button

### LINKED ISSUE #23: Add harvest button to the left panel.
Screenshot 2022-07-18 at 06 15 54

### PR DESCRIPTION
**Pull request by groninge01**
fixes #23 

image

### CODE REVIEW

**Comment by groninge01** [comment]
Maybe switch stuff around so it stays kind of grouped?

image

**Comment by danielmkm** [comment]
ya, switch it. I'll have another pass on that i think as well

**Comment by groninge01** [comment]
> ya, switch it. I'll have another pass on that i think as well

I have switched them around.

**Comment by danielmkm** [comment]
merge conflict sir, sorry

**Comment by groninge01** [comment]
fyi this is already messing with the fixed height

image

i'll add an issue for the graphs i'm working on and i'll also try to get a dynamic height then

**Pull request merged**
