### PR TITLE
fix: update dependencies

### PR DESCRIPTION
**Pull request by neverm25**
- Updated React.useMemo to use direct dependencies (pool, userInvestedBalances, prices), improving memoization efficiency.

### CODE REVIEW

**Comment by groninge01** [comment]
hey, thanks for the PR!

we're still doing this in a lot of places but we're also moving to a new app soon, so this one is kind of in maintenance mode :)

**Comment by neverm25** [comment]
Sounds interesting.
Could you tell me what the plan for the future app is?
I would like to contribute to your project.

**Comment by groninge01** [comment]
> Sounds interesting. Could you tell me what the plan for the future app is? I would like to contribute to your project.

We will probably be using this [one](https://github.com/balancer/frontend-v3).

**Comment by neverm25** [comment]
Great!
@groninge01 I would like to discuss with you how to collaborate
What do you think of this?

**Comment by groninge01** [comment]
> Great! @groninge01 I would like to discuss with you how to collaborate What do you think of this?

Well that repo is public so you can contribute in any way you like. If you have questions join the Balancer discord, go to the dev channel and ask em.

**Pull request merged**
