### PR TITLE
Update swap card UI

### PR DESCRIPTION
**Pull request by 1saf**

### CODE REVIEW

**Comment by danielmkm** [comment]
Was there motivation for doing an exterior border on the token select but not the swap modal? If not i'd probably lean towards no exterior border on both for consistency

Screenshot 2022-08-22 at 08 28 32
Screenshot 2022-08-22 at 08 27 45

**Comment by danielmkm** [comment]
Did a small cleanup pass, can't help but think the `sm` text is quite small, but i'm probably just getting old 

Screenshot 2022-08-22 at 09 07 03
Screenshot 2022-08-22 at 09 06 56

**Comment by danielmkm** [comment]
Flipped the bg color on the lower section to darker. Could totally just be me, but kinda like how it is on the trade card, where the lower section has a darker bg as its less prioirtized. 

Screenshot 2022-08-22 at 09 13 39
Screenshot 2022-08-22 at 09 13 28
Screenshot 2022-08-22 at 09 13 45

**Comment by 1saf** [comment]
Also think `sm` text is fine. UI is zoomable anyways.

**Pull request merged**
