### PR TITLE
Pool invest flow restyle.

### PR DESCRIPTION
**Pull request by 1saf**
Pool invest revamp. 

Still needs a few niggles fixing but the meat and potatoes is here. Will fill better description close to completion.

### CODE REVIEW

**Comment by danielmkm** [comment]
You'll need to change this tooltip to show only on eth/weth
Screenshot 2022-11-01 at 09 13 29

**Comment by danielmkm** [comment]
Custom investment is missing price impact

**Comment by groninge01** [comment]
image

Maybe just let the user use the slider instead of also being able to customize the amounts in the inputs below it?
(If the user really wants to customize the amount(s) they can always select the `custom investment` option on the previous screen)

**Comment by groninge01** [comment]
The styling of the slider isn't consistent.

image
image
image

Maybe also look at the styling of the rows below the sliders?

**Comment by groninge01** [comment]
Make the buttons the same size?

image

**Comment by groninge01** [comment]
image

`align-items: center`?

**Comment by groninge01** [comment]
Make the buttons the same size again:

image

This is how it is rn on beets.fi:

image

**Comment by groninge01** [comment]
Remove transparancy?

image

**Comment by groninge01** [comment]
I would also favor only showing the proportional option when it is supported.

**Comment by groninge01** [comment]
image

Maybe disable the input too when the user has no balance? And maybe also max it?

**Comment by groninge01** [comment]
Maybe disable the 'withdraw' button on the pool page when the user has no balance?

**Comment by danielmkm** [comment]
> image
> 
> Maybe just let the user use the slider instead of also being able to customize the amounts in the inputs below it? (If the user really wants to customize the amount(s) they can always select the `custom investment` option on the previous screen)

I'm fine with the inputs here, allows the user to provide an exact amount of 1 asset, where as the slider does not

**Comment by 1saf** [comment]
> The styling of the slider isn't consistent.
> 
> image image image
> 
> Maybe also look at the styling of the rows below the sliders?

Withdraw will be handled in a different PR

**Comment by 1saf** [comment]
> image
> 
> `align-items: center`?

Will be changed in different PR to update toasts

**Pull request merged**
